_wandb:
    value:
        cli_version: 0.25.1
        e:
            j7e8sppekol47c99tgskz5tel47rrtij:
                args:
                    - --config-file
                    - dinov2/configs/train/vit3d_highres.yaml
                    - --pretrained-weights
                    - /mnt/disk2/hieupc2/Stroke_project/code/baseline_encoder/3DINO/dinov2/weight/3dino_vit_weights.pth
                    - --output-dir
                    - /mnt/disk2/hieupc2/Stroke_project/code/baseline_encoder/3DINO/SOOP_result_image
                    - --dataset-name
                    - SOOP
                    - --base-data-dir
                    - /mnt/disk2/hieupc2/Stroke_project/code/datasets/fold
                    - --cache-dir
                    - /tmp/soop_cache
                    - --target-col
                    - gs_rankin_6isdeath
                    - --task-type
                    - regression
                    - --batch-size
                    - "4"
                    - --epochs
                    - "1"
                    - --epoch-length
                    - "1"
                    - --eval-period-iterations
                    - "1"
                    - --use-wandb
                codePath: dinov2/eval/linear3d_soop.py
                codePathLocal: dinov2/eval/linear3d_soop.py
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "470886195200"
                        used: "130675310592"
                email: phunghieu5c@gmail.com
                executable: /mnt/disk2/miniconda3/envs/hieupcvp/bin/python
                git:
                    commit: a91d8619c552f25c32f665818e1ab724634a793c
                    remote: git@github-hieupc:456alo8888/3DINO.git
                gpu: NVIDIA GeForce RTX 3080
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 8704
                      memoryTotal: "10737418240"
                      name: NVIDIA GeForce RTX 3080
                      uuid: GPU-df9358c9-e067-c84e-ffdd-d3a5006a4732
                    - architecture: Ampere
                      cudaCores: 8704
                      memoryTotal: "10737418240"
                      name: NVIDIA GeForce RTX 3080
                      uuid: GPU-e7be64cb-18fa-eb0d-842d-f68b73c9d624
                    - architecture: Ampere
                      cudaCores: 8704
                      memoryTotal: "10737418240"
                      name: NVIDIA GeForce RTX 3080
                      uuid: GPU-85e91cb8-9b83-d1d5-bb54-5747227b004e
                    - architecture: Ampere
                      cudaCores: 8704
                      memoryTotal: "10737418240"
                      name: NVIDIA GeForce RTX 3080
                      uuid: GPU-20c9c761-8835-6917-49ae-0fa1112a2010
                host: aiotlab
                memory:
                    total: "134789763072"
                os: Linux-6.17.0-14-generic-x86_64-with-glibc2.39
                program: /mnt/disk2/hieupc2/Stroke_project/code/baseline_encoder/3DINO/dinov2/eval/linear3d_soop.py
                python: CPython 3.12.7
                root: /mnt/disk2/hieupc2/Stroke_project/code/baseline_encoder/3DINO
                startedAt: "2026-03-19T09:07:58.616995Z"
                writerId: j7e8sppekol47c99tgskz5tel47rrtij
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 2
                - 3
                - 41
                - 48
                - 49
                - 51
            "2":
                - 1
                - 2
                - 3
                - 41
                - 48
                - 49
                - 51
            "3":
                - 2
                - 15
                - 16
            "4": 3.12.7
            "5": 0.25.1
            "12": 0.25.1
            "13": linux-x86_64
batch_size:
    value: 4
dataset_name:
    value: SOOP
epoch_length:
    value: 1
epochs:
    value: 1
learning_rate:
    value: 0.001
target_col:
    value: gs_rankin_6isdeath
task_type:
    value: regression
use_tabular:
    value: false
weight_decay:
    value: 0
