_wandb:
    value:
        cli_version: 0.25.1
        e:
            quneidow2y99odneuhv9ohabbws1cgab:
                args:
                    - --config-file
                    - dinov2/configs/train/vit3d_highres.yaml
                    - --pretrained-weights
                    - /mnt/disk2/hieupc2/Stroke_project/code/baseline_encoder/3DINO/dinov2/weight/3dino_vit_weights.pth
                    - --output-dir
                    - /mnt/disk2/hieupc2/Stroke_project/code/baseline_encoder/3DINO/outputs/soop_raw_gsrankin_image_only
                    - --dataset-name
                    - SOOP
                    - --base-data-dir
                    - /mnt/disk2/hieupc2/Stroke_project/code/datasets/fold_raw_trace
                    - --cache-dir
                    - /tmp/soop_raw_cache
                    - --target-col
                    - gs_rankin_6isdeath
                    - --task-type
                    - regression
                    - --wandb-run-name
                    - soop-raw-regression-gsrankin-image-only
                    - --batch-size
                    - "8"
                    - --epochs
                    - "1"
                    - --epoch-length
                    - "20"
                    - --eval-period-iterations
                    - "20"
                    - --optimizer
                    - auto
                    - --grad-clip-norm
                    - "1.0"
                    - --diagnostics-period
                    - "10"
                    - --normalize-features
                    - --strict-pretrained
                    - --use-wandb
                    - --wandb-project
                    - 3dino-soop-outcome-raw
                    - --wandb-mode
                    - online
                    - --wandb-tags
                    - soop,raw,regression
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "470886195200"
                        used: "167620526080"
                email: phunghieu5c@gmail.com
                executable: /mnt/disk2/miniconda3/envs/hieupcvp/bin/python
                git:
                    commit: a91d8619c552f25c32f665818e1ab724634a793c
                    remote: git@github-hieupc:456alo8888/3DINO.git
                gpu: NVIDIA GeForce RTX 3080
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 8704
                      memoryTotal: "10737418240"
                      name: NVIDIA GeForce RTX 3080
                      uuid: GPU-df9358c9-e067-c84e-ffdd-d3a5006a4732
                    - architecture: Ampere
                      cudaCores: 8704
                      memoryTotal: "10737418240"
                      name: NVIDIA GeForce RTX 3080
                      uuid: GPU-e7be64cb-18fa-eb0d-842d-f68b73c9d624
                    - architecture: Ampere
                      cudaCores: 8704
                      memoryTotal: "10737418240"
                      name: NVIDIA GeForce RTX 3080
                      uuid: GPU-85e91cb8-9b83-d1d5-bb54-5747227b004e
                    - architecture: Ampere
                      cudaCores: 8704
                      memoryTotal: "10737418240"
                      name: NVIDIA GeForce RTX 3080
                      uuid: GPU-20c9c761-8835-6917-49ae-0fa1112a2010
                host: aiotlab
                memory:
                    total: "134789763072"
                os: Linux-6.17.0-14-generic-x86_64-with-glibc2.39
                program: -m dinov2.eval.linear3d_soop
                python: CPython 3.12.7
                root: /mnt/disk2/hieupc2/Stroke_project/code/baseline_encoder/3DINO
                startedAt: "2026-03-19T19:41:21.787373Z"
                writerId: quneidow2y99odneuhv9ohabbws1cgab
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 2
                - 3
                - 41
                - 48
                - 49
                - 51
            "2":
                - 1
                - 2
                - 3
                - 41
                - 48
                - 49
                - 51
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.12.7
            "5": 0.25.1
            "12": 0.25.1
            "13": linux-x86_64
batch_size:
    value: 8
dataset_name:
    value: SOOP
diagnostics_period:
    value: 10
epoch_length:
    value: 20
epochs:
    value: 1
grad_clip_norm:
    value: 1
learning_rate:
    value: 0.001
normalize_features:
    value: true
optimizer:
    value: adamw
strict_pretrained:
    value: true
target_col:
    value: gs_rankin_6isdeath
task_type:
    value: regression
use_tabular:
    value: false
weight_decay:
    value: 0
